# MongoDB configuration with Docker Compose
version: '3.8'

services:
  # FastAPI Application with MongoDB
  api:
    build: .
    container_name: analytics-engineer-api-mongo
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Analytics Engineer API
      - APP_VERSION=1.0.0
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_TYPE=mongodb
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=analytics_engineer
      - MONGODB_COLLECTION=invoices
      - MIN_INVOICES_PER_REQUEST=2
      - MAX_INVOICES_PER_REQUEST=5
      - INCONSISTENCY_RATE=0.3
      - DUPLICATE_RATE=0.1
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - analytics-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: analytics-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=analytics_engineer
    volumes:
      - mongodb_data:/data/db
    networks:
      - analytics-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Mongo Express - Web UI for MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: analytics-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - analytics-network
    restart: unless-stopped

networks:
  analytics-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
